### ISSUE TITLE
How to understand num_diffusion_timesteps

### ISSUE THREAD

**Issue by superY688** [mirthAI/Fast-DDPM#11]
Hello,First of all, thanks for the great work and making it available to everyone.

I want to know what the num_diffusion_timesteps means and what its function is? Why do we need num_diffusion_timesteps when we have timesteps?

I would appreciate it if you could tell me more details.Thanks

**Comment by Sebastianjhx** [comment]
Hi there, _**num_diffusion_timesteps**_ refers to the total number of time steps in the diffusion process, while _**timesteps**_ specifies the subset of steps actually used. By default, the total number of diffusion time steps is set to 1000, but we use subsets such as 5, 10, 20, 50, or 100 steps out of the 1000. in this paper as our method. For more details, please refer to Figure 3 in our paper.

**Comment by superY688** [comment]
Thank you for your reply. I am very interested in the method in your paper. I would like to ask you, in your method, the forward diffusion process is still to gradually add noise at 1000 time steps, but the training and sampling process is only carried out at 10 time steps. Is this correct?
