### ISSUE TITLE
How to change the training process?

### ISSUE THREAD

**Issue by Lrihao0413** [mirthAI/Fast-DDPM#2]
First of all, congratulations on the great work, and thanks for making it open-source!

I'm in doubt about how to accelerate the training process? I have tried adjusting some parameters, but only accelerated the sampling speed, but the training speed remains the same. I hope to receive your answer. Thank you!

**Comment by Sebastianjhx** [comment]
Hi there, thanks for your interest in our works. Fast-DDPM speeds up the training process by achieving the better performance more quickly, in other words faster convergence. For more details, please refer to the result section in our paper. For instance in the task of image denoising, Fast-DDPM trained for 200,000 iterations could easily reach PSNR 37.0 and SSIM 0.91, while DDPM only reaches the best results of 35.4 and 0.87 at the iteration 600,000.
