### ISSUE TITLE
Incompatible dependencies

### ISSUE THREAD

**Issue by Mohinta2892** [mirthAI/Fast-DDPM#5]
Hello!

First of all, thank you very much for sharing your code for the amazing work!

I just wanted to highlight that it seems for `torch==1.12.1`, torchvision to install should be `torch==0.13.1`, instead of `torchvision==0.15.2`.
Otherwise, it does not install. 

Best,
Samia

**Comment by Sebastianjhx** [comment]
Hi there, thanks for pointing that out. We'll def update it later on.
