### ISSUE TITLE
How to train on my own datasets for image denoising

### ISSUE THREAD

**Issue by superY688** [mirthAI/Fast-DDPM#6]
Hello,First of all, thanks for the great work and making it available to everyone.

I am interested in image denoising,I want to know to how to train my own datasets for image denoising. 

I would appreciate it if you could tell me.Thanks

**Comment by Sebastianjhx** [comment]
Hi there, thanks for your interest in our work.

For the purpose of training a customized dataset for an image denoising task, first ensure that your dataset with paired images is ready in the 'data' folder. Then, update the data root directory in the configuration file. And you also need to write you own dataset scripts in the 'dataset' folder.

Feel free to leave more comments regarding any other issues.

**Comment by superY688** [comment]
> Hi there, thanks for your interest in our work.
> 
> For the purpose of training a customized dataset for an image denoising task, first ensure that your dataset with paired images is ready in the 'data' folder. Then, update the data root directory in the configuration file. And you also need to write you own dataset scripts in the 'dataset' folder.
> 
> Feel free to leave more comments regarding any other issues.


Thank you so much for your reply.I have trained a customized dataset through the method presented in the paper.
However，model denoising is not good on my customized dataset. The loss has been fluctuating，the psnr value of the denoised image is only 15 ，I do not know  how to improve it.
Can you provide me with the LDFDCT‘s training logs？
I would appreciate it if you could reply to me.

**Comment by Sebastianjhx** [comment]
In this case, is your dataset medical related? How many time steps out of 1000 are you using and how many iterations have you trained the model?

**Comment by superY688** [comment]
> In this case, is your dataset medical related? How many time steps out of 1000 are you using and how many iterations have you trained the model?

Many thanks for your prompt response

My dataset is not medical related.I use 10 time steps out of 1000.I trained the model for 110000steps.The length of my dataset is 2500.

Do datasets have to be medical related, and what part of the code should I change if I want to use datasets from other fields.

Thank you very much for your kindness，your assistance means the world to me.

**Comment by Sebastianjhx** [comment]
So far all datasets used in our experiments are medical related, and we haven't extend our model to non-medical fields yet. However, we suppose our model should apply to all grayscale data in this scenario without changes. My suggestion would be training the models for longer periods to observe the changes and experimenting with different numbers of timesteps (20, 50, 100 out of 1000).

**Comment by superY688** [comment]
> So far all datasets used in our experiments are medical related, and we haven't extend our model to non-medical fields yet. However, we suppose our model should apply to all grayscale data in this scenario without changes. My suggestion would be training the models for longer periods to observe the changes and experimenting with different numbers of timesteps (20, 50, 100 out of 1000). And please make sure your data is properly preprocessed before feeding into the model.

Many thanks for your prompt response.My datasets are gray,but the loss value fluctuates and does not converge when i train the moel.Can you provide me some information about the loss value When you train the model on CT datasets.

Thank you very much for your kindness，your assistance means the world to me.
