### ISSUE TITLE
brats dataset

### ISSUE THREAD

**Issue by LingkaiLiu** [mirthAI/Fast-DDPM#8]
Hello,

First of all, thanks for the great work.
I would like to know if all the 2D slices are used when using the BRATS dataset, for example, a patient can get 155 slices, and all 155 slices are used for training?

**Comment by Sebastianjhx** [comment]
Hi we partitioned all patients into train set and test set, where all slices of each patient were used.

**Comment by LingkaiLiu** [comment]
thanks
